apiVersion: v1
kind: Pod
metadata:
  name: working-app-pod
  labels:
    name: working-app-pod
    app: demo-voting-app

spec:
  containers:
    - name: working-app
      image: dockersamples/examplevotingapp_worker


